### ISSUE TITLE
kubectl unknown flag (--short) for github runners

### ISSUE THREAD

**Issue by chineduugbaja** [huaweicloud/cce-credential-action#1]
Hi Team, 

I experience this when attempting to use cce-credential-action. This is not passed in my workflow but as a test from the action. The flag has been deprecated, can this be removed

<img width="1252" alt="Screenshot 2024-05-10 at 12 02 25 AM" src="https://github.com/huaweicloud/cce-credential-action/assets/104582970/520d993b-66d2-4423-9c84-21817594a4c6">

**Comment by JimohHWC** [comment]
please use the huaweicloud/cce-credential-action@v1.0.2 just released
